export const SHOW_PRODUCTS = 'SHOW_PRODUCTS';
export const GET_PRODUCT_NAME = 'GET_PRODUCT_NAME';
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const VALIDATION_USER = 'VALIDATION_USER';
export const ADD_PRODUCT = 'ADD_PRODUCT';
