/////////////////////////////// AQUI VA LA CONEXION A STRIPE
// AGREGAR UN CUADRO DE TOTAL QUE TENGA EL BOTO DE COMPRAR
// Y CONECTARLO A STRIPE
// Y QUE TENGA EL VALOR TOTAL DE TODOS LOS SUBTOTALES DE LOS PRODUCTOS!!